# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tjaskula.github.io
gitlocation: https://github.com/tjaskula/tjaskula.github.io.git
gitbranch: master
title: Tomasz Jaskula's blog
description: >
    F# and functional programming is the topic I'm interested in and passionate about at the moment.
    However, software architecture, software craftsmanship, Domain Driven Design
    are also topics dear to my heart. I don't restrict myself to talk only about these
    but will pick up topics that are of interest to me :)

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes